backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
    - name: 'schemes' 
      label: 'Completed Schemes'
      label_singular: 'Scheme'
      editor:
          preview: false
      delete: false
      preview_path: 'scheme'
      files:
          - label: 'Schemes'
            name: 'schemes'
            file: 'data/schemes.json'
            fields:
                - label: Schemes
                  name: schemes
                  widget: list
                  allow_add: true
                  fields:
                      - { label: 'Reference', name: 'reference', widget: 'string' }
                      - label: 'Image'
                        name: 'image'
                        widget: 'object'
                        fields:
                            - { label: 'Photo', name: 'main', widget: 'image' }
                            - { label: 'Photo Alt', name: 'alt', widget: 'image' }
                      - { label: 'Description', name: 'description', widget: 'string' }
                      - { label: 'Address', name: 'address', widget: 'string' }
                      - { label: 'Completion date', name: 'completion', widget: 'string' }
                      - label: 'Social Rent'
                        name: 'social'
                        widget: 'list'
                        fields:
                            - { label: 'Address', name: 'address', widget: 'string' }
                            - { label: 'UPRN', name: 'uprn', widget: 'string' }
